version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mah-diamonds-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_SITE_URL=https://mahdiamonds.co.uk
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
