"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Archive, BarChart3, Bell, BookOpen, CalendarDays, ChevronDown, CircleDollarSign, Diamond, ExternalLink, FileText, Gem, Inbox, LayoutDashboard, Package, Pencil, Plus, Search, Settings, ShoppingBag, Sparkles, Trash2, Users } from "lucide-react";
import { toast } from "sonner";
import { products as storefrontProducts, diamonds as storefrontDiamonds, money, type Product } from "@/lib/demo-data";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Switch } from "@/components/ui/switch";

type AdminProduct = Product & { sku: string; stock: number; status: "Active" | "Draft" | "Archived"; featured: boolean };
type Order = { id: string; customer: string; email: string; total: number; date: string; status: "New" | "Preparing" | "Ready" | "Completed" | "Cancelled"; items: number };
type Enquiry = { id: string; name: string; subject: string; date: string; status: "New" | "In progress" | "Closed" };
type Appointment = { id: string; name: string; type: string; date: string; time: string; status: "Requested" | "Confirmed" | "Completed" | "Cancelled" };
type Article = { id: string; title: string; category: string; status: "Published" | "Draft"; updated: string };
type AdminState = { products: AdminProduct[]; orders: Order[]; enquiries: Enquiry[]; appointments: Appointment[]; articles: Article[]; settings: { storeOpen: boolean; appointmentsOpen: boolean; currency: string; lowStock: number; announcement: string } };

const seedState: AdminState = {
  products: storefrontProducts.map((product, index) => ({ ...product, sku: product.id, stock: [4, 2, 7, 1, 8, 3, 6, 5, 9, 2][index] || 3, status: index === 3 ? "Draft" : "Active", featured: Boolean(product.badge) })),
  orders: [
    { id: "MAH-1048", customer: "Amelia Hart", email: "amelia@example.com", total: 8650, date: "11 Sep 2026", status: "New", items: 1 },
    { id: "MAH-1047", customer: "Theo James", email: "theo@example.com", total: 2630, date: "10 Sep 2026", status: "Preparing", items: 2 },
    { id: "MAH-1046", customer: "Sofia Noor", email: "sofia@example.com", total: 1450, date: "09 Sep 2026", status: "Ready", items: 1 },
    { id: "MAH-1045", customer: "Oliver Reed", email: "oliver@example.com", total: 980, date: "08 Sep 2026", status: "Completed", items: 1 },
  ],
  enquiries: [
    { id: "ENQ-238", name: "Nadia Khan", subject: "Bespoke engagement ring", date: "Today, 10:42", status: "New" },
    { id: "ENQ-237", name: "Ethan Cole", subject: "Diamond guidance", date: "Yesterday, 16:20", status: "In progress" },
    { id: "ENQ-236", name: "Hana Malik", subject: "Wedding ring sizing", date: "09 Sep, 11:05", status: "Closed" },
  ],
  appointments: [
    { id: "APT-092", name: "Iris Bennett", type: "Engagement rings", date: "15 Sep 2026", time: "10:00", status: "Requested" },
    { id: "APT-091", name: "Adam Farooq", type: "Bespoke", date: "15 Sep 2026", time: "12:30", status: "Confirmed" },
    { id: "APT-090", name: "Maya Lewis", type: "Jewellery", date: "17 Sep 2026", time: "15:00", status: "Confirmed" },
  ],
  articles: [
    { id: "ART-01", title: "A considered guide to diamond shapes", category: "Education", status: "Published", updated: "11 Sep 2026" },
    { id: "ART-02", title: "Inside the MAH design conversation", category: "The Atelier", status: "Draft", updated: "10 Sep 2026" },
    { id: "ART-03", title: "Choosing a wedding ring together", category: "Guides", status: "Published", updated: "07 Sep 2026" },
  ],
  settings: { storeOpen: true, appointmentsOpen: true, currency: "GBP", lowStock: 3, announcement: "Book a personal appointment with an MAH expert." },
};

const nav = [
  { id: "overview", label: "Overview", icon: LayoutDashboard },
  { id: "products", label: "Products", icon: Gem },
  { id: "diamonds", label: "Diamonds", icon: Diamond },
  { id: "orders", label: "Orders", icon: ShoppingBag, count: 1 },
  { id: "clients", label: "Clients", icon: Users },
  { id: "appointments", label: "Appointments", icon: CalendarDays, count: 1 },
  { id: "enquiries", label: "Enquiries", icon: Inbox, count: 1 },
  { id: "journal", label: "Journal & pages", icon: BookOpen },
  { id: "settings", label: "Settings", icon: Settings },
];

function useAdminState() {
  const [state, setState] = useState<AdminState>(seedState);
  const [ready, setReady] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { try { const saved = localStorage.getItem("mah-admin-demo"); if (saved) setState(JSON.parse(saved)); } catch {} setReady(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (ready) localStorage.setItem("mah-admin-demo", JSON.stringify(state)); }, [state, ready]);
  return [state, setState] as const;
}

function StatusBadge({ value }: { value: string }) {
  const tone = ["Active", "Published", "Completed", "Closed", "Confirmed"].includes(value) ? "good" : ["New", "Requested", "Ready"].includes(value) ? "attention" : ["Cancelled", "Archived"].includes(value) ? "muted" : "neutral";
  return <span className={`admin-status ${tone}`}><i />{value}</span>;
}

function Metric({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: typeof BarChart3 }) {
  return <article className="admin-metric"><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div><Icon /></article>;
}

function Overview({ state, go }: { state: AdminState; go: (id: string) => void }) {
  const revenue = state.orders.filter((o) => o.status !== "Cancelled").reduce((sum, order) => sum + order.total, 0);
  return <><div className="admin-metrics"><Metric label="Sample revenue" value={money(revenue)} note="Across seeded demonstration orders" icon={CircleDollarSign} /><Metric label="Open orders" value={String(state.orders.filter((o) => !["Completed", "Cancelled"].includes(o.status)).length)} note="1 requires attention today" icon={ShoppingBag} /><Metric label="Catalogue" value={String(state.products.length + storefrontDiamonds.length)} note={`${state.products.filter((p) => p.stock <= state.settings.lowStock).length} low-stock pieces`} icon={Package} /><Metric label="Client requests" value={String(state.enquiries.filter((e) => e.status !== "Closed").length + state.appointments.filter((a) => a.status === "Requested").length)} note="Enquiries and appointments" icon={Users} /></div><div className="admin-overview-grid"><section className="admin-card admin-chart"><div className="admin-card-head"><div><p>Store performance</p><h2>Seven-day activity</h2></div><span>Sample analytics</span></div><div className="bar-chart" aria-label="Sample seven day order activity">{[38, 54, 42, 72, 58, 88, 66].map((height, index) => <div key={index}><i style={{ height: `${height}%` }} /><span>{["Fri", "Sat", "Sun", "Mon", "Tue", "Wed", "Thu"][index]}</span></div>)}</div></section><section className="admin-card"><div className="admin-card-head"><div><p>Attention</p><h2>What needs you</h2></div></div><button className="attention-row" onClick={() => go("orders")}><span><ShoppingBag />New order awaiting review</span><strong>1</strong></button><button className="attention-row" onClick={() => go("appointments")}><span><CalendarDays />Appointment request</span><strong>1</strong></button><button className="attention-row" onClick={() => go("products")}><span><Archive />Low-stock catalogue items</span><strong>{state.products.filter((p) => p.stock <= state.settings.lowStock).length}</strong></button><button className="attention-row" onClick={() => go("enquiries")}><span><Inbox />New client enquiry</span><strong>1</strong></button></section></div><section className="admin-card"><div className="admin-card-head"><div><p>Latest activity</p><h2>Recent orders</h2></div><button onClick={() => go("orders")}>View all <ExternalLink size={14} /></button></div><OrdersTable orders={state.orders.slice(0, 4)} /></section></>;
}

function OrdersTable({ orders, onStatus }: { orders: Order[]; onStatus?: (id: string, status: Order["status"]) => void }) {
  return <Table className="admin-table"><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>Client</TableHead><TableHead>Date</TableHead><TableHead>Items</TableHead><TableHead>Total</TableHead><TableHead>Status</TableHead>{onStatus && <TableHead>Update</TableHead>}</TableRow></TableHeader><TableBody>{orders.map((order) => <TableRow key={order.id}><TableCell><strong>{order.id}</strong></TableCell><TableCell><span className="admin-person">{order.customer}<small>{order.email}</small></span></TableCell><TableCell>{order.date}</TableCell><TableCell>{order.items}</TableCell><TableCell><strong>{money(order.total)}</strong></TableCell><TableCell><StatusBadge value={order.status} /></TableCell>{onStatus && <TableCell><select value={order.status} onChange={(e) => onStatus(order.id, e.target.value as Order["status"])}><option>New</option><option>Preparing</option><option>Ready</option><option>Completed</option><option>Cancelled</option></select></TableCell>}</TableRow>)}</TableBody></Table>;
}

function ProductsView({ state, setState }: { state: AdminState; setState: React.Dispatch<React.SetStateAction<AdminState>> }) {
  const [search, setSearch] = useState(""); const [editing, setEditing] = useState<AdminProduct | null>(null); const [deleting, setDeleting] = useState<AdminProduct | null>(null);
  const filtered = state.products.filter((p) => `${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(search.toLowerCase()));
  const save = (product: AdminProduct) => { setState((current) => ({ ...current, products: current.products.some((p) => p.id === product.id) ? current.products.map((p) => p.id === product.id ? product : p) : [product, ...current.products] })); setEditing(null); toast.success("Sample catalogue updated"); };
  const create = () => setEditing({ id: `MAH-${Date.now().toString().slice(-5)}`, sku: `MAH-${Date.now().toString().slice(-5)}`, name: "New sample piece", category: "jewellery", style: "Ring", metal: "18k Yellow Gold", price: 1200, description: "Add the approved product description.", image: "/images/mah-hero-concept.png", stock: 1, status: "Draft", featured: false });
  return <><div className="admin-toolbar"><label className="admin-search"><Search /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search products or SKU" /></label><button className="admin-primary" onClick={create}><Plus />Add product</button></div><section className="admin-card"><Table className="admin-table"><TableHeader><TableRow><TableHead>Piece</TableHead><TableHead>Category</TableHead><TableHead>Sample price</TableHead><TableHead>Stock</TableHead><TableHead>Status</TableHead><TableHead>Featured</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{filtered.map((product) => <TableRow key={product.id}><TableCell><span className="admin-person"><strong>{product.name}</strong><small>{product.sku} · {product.metal}</small></span></TableCell><TableCell className="admin-capitalize">{product.category}</TableCell><TableCell>{money(product.price)}</TableCell><TableCell><span className={product.stock <= state.settings.lowStock ? "stock-low" : ""}>{product.stock}</span></TableCell><TableCell><StatusBadge value={product.status} /></TableCell><TableCell><Switch checked={product.featured} onCheckedChange={(featured) => setState((current) => ({ ...current, products: current.products.map((p) => p.id === product.id ? { ...p, featured } : p) }))} /></TableCell><TableCell><div className="row-actions"><button onClick={() => setEditing(product)} aria-label={`Edit ${product.name}`}><Pencil /></button><button onClick={() => setDeleting(product)} aria-label={`Archive ${product.name}`}><Trash2 /></button></div></TableCell></TableRow>)}</TableBody></Table></section><ProductDialog product={editing} onClose={() => setEditing(null)} onSave={save} /><AlertDialog open={Boolean(deleting)} onOpenChange={(open) => !open && setDeleting(null)}><AlertDialogContent className="admin-dialog"><AlertDialogHeader><AlertDialogTitle>Archive this sample product?</AlertDialogTitle><AlertDialogDescription>It will be removed from the current admin catalogue. This demonstration change can be reset from Settings.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={() => { if (deleting) setState((current) => ({ ...current, products: current.products.filter((p) => p.id !== deleting.id) })); setDeleting(null); toast.success("Sample product archived"); }}>Archive</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}

function ProductDialog({ product, onClose, onSave }: { product: AdminProduct | null; onClose: () => void; onSave: (product: AdminProduct) => void }) {
  if (!product) return null;
  return <ProductDialogForm key={product.id} product={product} onClose={onClose} onSave={onSave} />;
}

function ProductDialogForm({ product, onClose, onSave }: { product: AdminProduct; onClose: () => void; onSave: (product: AdminProduct) => void }) {
  const [draft, setDraft] = useState<AdminProduct>(product);
  return <Dialog open={Boolean(product)} onOpenChange={(open) => !open && onClose()}><DialogContent className="admin-dialog product-editor"><DialogHeader><DialogTitle>{statefulName(product) ? "Edit product" : "Add product"}</DialogTitle><DialogDescription>Manage the sample storefront record. Product media uploads will connect to managed object storage.</DialogDescription></DialogHeader><div className="admin-form"><label className="wide">Product name<input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></label><label>SKU<input value={draft.sku} onChange={(e) => setDraft({ ...draft, sku: e.target.value })} /></label><label>Category<select value={draft.category} onChange={(e) => setDraft({ ...draft, category: e.target.value as Product["category"] })}><option value="engagement">Engagement</option><option value="wedding">Wedding</option><option value="jewellery">Jewellery</option></select></label><label>Metal<input value={draft.metal} onChange={(e) => setDraft({ ...draft, metal: e.target.value })} /></label><label>Style<input value={draft.style} onChange={(e) => setDraft({ ...draft, style: e.target.value })} /></label><label>Sample price<input type="number" value={draft.price} onChange={(e) => setDraft({ ...draft, price: Number(e.target.value) })} /></label><label>Stock<input type="number" value={draft.stock} onChange={(e) => setDraft({ ...draft, stock: Number(e.target.value) })} /></label><label>Status<select value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value as AdminProduct["status"] })}><option>Active</option><option>Draft</option><option>Archived</option></select></label><label className="wide">Description<textarea value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} /></label></div><DialogFooter><button className="admin-secondary" onClick={onClose}>Cancel</button><button className="admin-primary" onClick={() => onSave(draft)}>Save product</button></DialogFooter></DialogContent></Dialog>;
}

function statefulName(product: AdminProduct) { return !product.name.startsWith("New sample"); }

function DiamondsView() {
  const [type, setType] = useState("All");
  const list = storefrontDiamonds.filter((d) => type === "All" || d.type === type);
  return <><div className="admin-toolbar"><div className="admin-segment">{["All", "Natural", "Lab-grown"].map((item) => <button className={type === item ? "active" : ""} key={item} onClick={() => setType(item)}>{item}</button>)}</div><button className="admin-primary"><Plus />Import inventory</button></div><section className="admin-card"><Table className="admin-table"><TableHeader><TableRow><TableHead>Reference</TableHead><TableHead>Type</TableHead><TableHead>Shape</TableHead><TableHead>Carat</TableHead><TableHead>Colour</TableHead><TableHead>Clarity</TableHead><TableHead>Cut</TableHead><TableHead>Sample price</TableHead><TableHead>Availability</TableHead></TableRow></TableHeader><TableBody>{list.map((diamond) => <TableRow key={diamond.id}><TableCell><strong>{diamond.id}</strong></TableCell><TableCell>{diamond.type}</TableCell><TableCell>{diamond.shape}</TableCell><TableCell>{diamond.carat.toFixed(2)}</TableCell><TableCell>{diamond.colour}</TableCell><TableCell>{diamond.clarity}</TableCell><TableCell>{diamond.cut}</TableCell><TableCell>{money(diamond.price)}</TableCell><TableCell><StatusBadge value="Active" /></TableCell></TableRow>)}</TableBody></Table></section><div className="admin-callout"><Sparkles /><div><strong>Inventory connector ready</strong><p>CSV/API import, certificate media and live reservation hooks belong here once MAH confirms its diamond supplier.</p></div></div></>;
}

function SimpleRecords({ kind, state, setState }: { kind: "appointments" | "enquiries" | "journal"; state: AdminState; setState: React.Dispatch<React.SetStateAction<AdminState>> }) {
  if (kind === "appointments") return <section className="admin-card"><Table className="admin-table"><TableHeader><TableRow><TableHead>Reference</TableHead><TableHead>Client</TableHead><TableHead>Subject</TableHead><TableHead>Date</TableHead><TableHead>Time</TableHead><TableHead>Status</TableHead><TableHead>Update</TableHead></TableRow></TableHeader><TableBody>{state.appointments.map((item) => <TableRow key={item.id}><TableCell><strong>{item.id}</strong></TableCell><TableCell>{item.name}</TableCell><TableCell>{item.type}</TableCell><TableCell>{item.date}</TableCell><TableCell>{item.time}</TableCell><TableCell><StatusBadge value={item.status} /></TableCell><TableCell><select value={item.status} onChange={(e) => setState((current) => ({ ...current, appointments: current.appointments.map((a) => a.id === item.id ? { ...a, status: e.target.value as Appointment["status"] } : a) }))}><option>Requested</option><option>Confirmed</option><option>Completed</option><option>Cancelled</option></select></TableCell></TableRow>)}</TableBody></Table></section>;
  if (kind === "enquiries") return <section className="admin-card"><Table className="admin-table"><TableHeader><TableRow><TableHead>Reference</TableHead><TableHead>Client</TableHead><TableHead>Subject</TableHead><TableHead>Received</TableHead><TableHead>Status</TableHead><TableHead>Update</TableHead></TableRow></TableHeader><TableBody>{state.enquiries.map((item) => <TableRow key={item.id}><TableCell><strong>{item.id}</strong></TableCell><TableCell>{item.name}</TableCell><TableCell>{item.subject}</TableCell><TableCell>{item.date}</TableCell><TableCell><StatusBadge value={item.status} /></TableCell><TableCell><select value={item.status} onChange={(e) => setState((current) => ({ ...current, enquiries: current.enquiries.map((a) => a.id === item.id ? { ...a, status: e.target.value as Enquiry["status"] } : a) }))}><option>New</option><option>In progress</option><option>Closed</option></select></TableCell></TableRow>)}</TableBody></Table></section>;
  return <><div className="admin-toolbar"><span>Manage editorial stories and core page copy.</span><button className="admin-primary"><Plus />New article</button></div><section className="admin-card"><Table className="admin-table"><TableHeader><TableRow><TableHead>Article</TableHead><TableHead>Category</TableHead><TableHead>Updated</TableHead><TableHead>Status</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{state.articles.map((item) => <TableRow key={item.id}><TableCell><span className="admin-person"><strong>{item.title}</strong><small>{item.id}</small></span></TableCell><TableCell>{item.category}</TableCell><TableCell>{item.updated}</TableCell><TableCell><StatusBadge value={item.status} /></TableCell><TableCell><button className="icon-button"><Pencil /></button></TableCell></TableRow>)}</TableBody></Table></section></>;
}

function ClientsView({ state }: { state: AdminState }) {
  const clients = [...new Map(state.orders.map((order) => [order.email, order])).values()];
  return <section className="admin-card"><Table className="admin-table"><TableHeader><TableRow><TableHead>Client</TableHead><TableHead>Latest order</TableHead><TableHead>Order value</TableHead><TableHead>Relationship</TableHead></TableRow></TableHeader><TableBody>{clients.map((client) => <TableRow key={client.email}><TableCell><span className="admin-person"><strong>{client.customer}</strong><small>{client.email}</small></span></TableCell><TableCell>{client.id}</TableCell><TableCell>{money(client.total)}</TableCell><TableCell><StatusBadge value={client.status === "Completed" ? "Client" : "Active order"} /></TableCell></TableRow>)}</TableBody></Table></section>;
}

function SettingsView({ state, setState }: { state: AdminState; setState: React.Dispatch<React.SetStateAction<AdminState>> }) {
  const settings = state.settings; const update = (patch: Partial<AdminState["settings"]>) => setState((current) => ({ ...current, settings: { ...current.settings, ...patch } }));
  return <div className="settings-grid"><section className="admin-card settings-panel"><p>Store controls</p><h2>Commerce availability</h2><label className="setting-row"><span><strong>Storefront ordering</strong><small>Allow customers to begin checkout</small></span><Switch checked={settings.storeOpen} onCheckedChange={(storeOpen) => update({ storeOpen })} /></label><label className="setting-row"><span><strong>Appointment requests</strong><small>Show booking availability</small></span><Switch checked={settings.appointmentsOpen} onCheckedChange={(appointmentsOpen) => update({ appointmentsOpen })} /></label><label className="setting-field">Display currency<select value={settings.currency} onChange={(e) => update({ currency: e.target.value })}><option>GBP</option><option>USD</option><option>AED</option><option>EUR</option></select></label><label className="setting-field">Low-stock alert at<input type="number" value={settings.lowStock} onChange={(e) => update({ lowStock: Number(e.target.value) })} /></label></section><section className="admin-card settings-panel"><p>Storefront message</p><h2>Announcement bar</h2><label className="setting-field">Current message<textarea value={settings.announcement} onChange={(e) => update({ announcement: e.target.value })} /></label><button className="admin-primary" onClick={() => toast.success("Sample settings saved locally")}>Save settings</button></section><section className="admin-card settings-panel"><p>Production connections</p><h2>Integration readiness</h2>{["Payment provider", "Email delivery", "Shipping & tax", "Diamond inventory", "Media storage", "Analytics"].map((item) => <div className="integration-row" key={item}><span>{item}</span><StatusBadge value="Awaiting credentials" /></div>)}</section><section className="admin-card settings-panel danger-panel"><p>Demo data</p><h2>Reset this control centre</h2><p>Restore all sample products, orders, requests and settings to their original state.</p><button className="admin-secondary" onClick={() => { localStorage.removeItem("mah-admin-demo"); location.reload(); }}>Reset sample data</button></section></div>;
}

function OrdersView({ state, setState }: { state: AdminState; setState: React.Dispatch<React.SetStateAction<AdminState>> }) {
  const [filter, setFilter] = useState("All"); const orders = state.orders.filter((o) => filter === "All" || o.status === filter);
  return <><div className="admin-toolbar"><div className="admin-segment">{["All", "New", "Preparing", "Ready", "Completed"].map((item) => <button className={filter === item ? "active" : ""} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><button className="admin-secondary"><FileText />Export</button></div><section className="admin-card"><OrdersTable orders={orders} onStatus={(id, status) => { setState((current) => ({ ...current, orders: current.orders.map((o) => o.id === id ? { ...o, status } : o) })); toast.success("Sample order status updated"); }} /></section></>;
}

const titles: Record<string, [string, string]> = { overview: ["Good afternoon", "A focused view of today’s MAH activity."], products: ["Products", "Manage catalogue pieces, pricing and availability."], diamonds: ["Diamond inventory", "Review sample stones and prepare live supplier imports."], orders: ["Orders", "Track every order from payment review to fulfilment."], clients: ["Clients", "A relationship-led view of purchasers and active orders."], appointments: ["Appointments", "Confirm and manage personal consultations."], enquiries: ["Expert enquiries", "Keep every client conversation moving."], journal: ["Journal & pages", "Control editorial stories and core website content."], settings: ["Settings", "Store availability, messaging and production connections."] };

export function AdminPortal({ initialSection, userName, demoMode }: { initialSection: string; userName: string; demoMode: boolean }) {
  const router = useRouter(); const active = titles[initialSection] ? initialSection : "overview"; const [state, setState] = useAdminState();
  const go = (id: string) => router.push(id === "overview" ? "/admin" : `/admin/${id}`);
  const content = active === "overview" ? <Overview state={state} go={go} /> : active === "products" ? <ProductsView state={state} setState={setState} /> : active === "diamonds" ? <DiamondsView /> : active === "orders" ? <OrdersView state={state} setState={setState} /> : active === "clients" ? <ClientsView state={state} /> : active === "appointments" || active === "enquiries" || active === "journal" ? <SimpleRecords kind={active} state={state} setState={setState} /> : <SettingsView state={state} setState={setState} />;
  return <div className="admin-app"><SidebarProvider><Sidebar collapsible="offcanvas" className="admin-sidebar"><SidebarHeader><Link href="/admin" className="admin-brand"><span>MAH</span><small>Administration</small></Link></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>Operations</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{nav.map(({ id, label, icon: Icon, count }) => <SidebarMenuItem key={id}><SidebarMenuButton isActive={active === id} onClick={() => go(id)} tooltip={label}><Icon /><span>{label}</span>{count ? <em>{count}</em> : null}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter><Link href="/" className="admin-view-store"><ExternalLink />View storefront</Link><div className="admin-user"><span>{userName.slice(0, 1).toUpperCase()}</span><div><strong>{userName}</strong><small>{demoMode ? "Local demo access" : "Authorised administrator"}</small></div></div></SidebarFooter></Sidebar><SidebarInset className="admin-main"><header className="admin-topbar"><SidebarTrigger /><div className="admin-breadcrumb"><span>MAH</span><ChevronDown /><strong>{active === "overview" ? "Overview" : titles[active][0]}</strong></div><div className="admin-top-actions"><Link href="/" title="View storefront"><ExternalLink /></Link><button title="Notifications"><Bell /><i /></button></div></header>{demoMode && <div className="admin-demo-banner"><Sparkles />Demonstration administration — sample records are stored only in this browser.</div>}<div className="admin-content"><div className="admin-page-head"><div><p>{active === "overview" ? new Date().toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long" }) : "MAH Administration"}</p><h1>{titles[active][0]}{active === "overview" ? `, ${userName.split(" ")[0]}.` : ""}</h1><span>{titles[active][1]}</span></div>{active === "overview" && <button className="admin-primary" onClick={() => go("products")}><Plus />Add a product</button>}</div>{content}</div></SidebarInset></SidebarProvider></div>;
}
