export type Product = {
  id: string;
  name: string;
  category: "engagement" | "wedding" | "jewellery";
  style: string;
  collection?: string;
  metal: string;
  availableMetals?: string[];
  price: number;
  description: string;
  image: string;
  images?: string[];
  metalImages?: Record<string, string>;
  badge?: string;
  compatibleShapes?: string[];
  settingDetails?: string[];
  gender?: "women" | "men" | "unisex";
  subCategory?: string;
  width?: string;
  profile?: string;
  isDiamond?: boolean;
};

export type Diamond = {
  id: string;
  type: "Natural" | "Lab-grown";
  shape: string;
  carat: number;
  colour: string;
  clarity: string;
  cut: string;
  certificate: "GIA" | "IGI";
  reportNumber?: string;
  price: number;
  polish?: "Excellent" | "Very Good" | "Good";
  symmetry?: "Excellent" | "Very Good" | "Good";
  fluorescence?: "None" | "Faint" | "Medium" | "Strong";
  depth?: number;
  table?: number;
  measurements?: string;
  ratio?: number;
  culet?: string;
  girdle?: string;
  status?: "available" | "reserved" | "sold";
  reservedUntil?: string;
};

export const products: Product[] = [
  // ==========================================
  // ENGAGEMENT RINGS (Section 05A & 05B)
  // ==========================================
  {
    id: "ER-000",
    name: "The Aurora",
    category: "engagement",
    style: "Solitaire",
    collection: "Maison Sovereign",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k White Gold", "18k Yellow Gold", "18k Rose Gold"],
    price: 1950,
    description: "A timeless solitaire with refined proportions that highlight the beauty of your centre diamond.",
    image: "/images/styles/solitaire.jpg",
    images: [
      "/images/styles/solitaire.jpg",
      "/images/mah-hero-concept.png",
      "/images/metals/platinum.jpg",
      "/images/mah-atelier-concept.png",
      "/images/mah-atelier-sketch.jpg",
    ],
    metalImages: {
      "Platinum": "/images/styles/solitaire.jpg",
      "18k White Gold": "/images/metals/white-gold.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
    },
    badge: "Maison Masterpiece",
    compatibleShapes: ["Round", "Oval", "Cushion", "Princess", "Emerald", "Pear", "Marquise", "Radiant", "Asscher"],
    settingDetails: ["Plain Band"],
  },
  {
    id: "ER-010",
    name: "Solitaire Classic",
    category: "engagement",
    style: "Solitaire",
    collection: "Classic Collection",
    metal: "18k White Gold",
    availableMetals: ["18k White Gold", "18k Yellow Gold", "18k Rose Gold", "Platinum"],
    price: 1450,
    description: "A refined four-prong solitaire with a polished knife-edge band crafted to elevate a brilliant round centre stone.",
    image: "/images/styles/solitaire.jpg",
    images: ["/images/styles/solitaire.jpg", "/images/mah-hero-concept.png"],
    metalImages: {
      "18k White Gold": "/images/styles/solitaire.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
      "Platinum": "/images/metals/platinum.jpg",
    },
    badge: "Maison Icon",
    compatibleShapes: ["Round"],
    settingDetails: ["Plain Band"],
  },
  {
    id: "ER-011",
    name: "Halo Grace",
    category: "engagement",
    style: "Halo",
    collection: "Celeste Collection",
    metal: "18k White Gold",
    availableMetals: ["18k White Gold", "18k Yellow Gold", "18k Rose Gold", "Platinum"],
    price: 2450,
    description: "A delicate micropavé halo with hand-set pavé shoulders, capturing light from every angle.",
    image: "/images/styles/halo.jpg",
    images: ["/images/styles/halo.jpg", "/images/mah-hero-concept.png"],
    metalImages: {
      "18k White Gold": "/images/styles/halo.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
      "Platinum": "/images/metals/platinum.jpg",
    },
    badge: "London Classic",
    compatibleShapes: ["Round", "Cushion", "Oval"],
    settingDetails: ["Cathedral Setting", "Plain Band"],
  },
  {
    id: "ER-012",
    name: "Emerald Elegance",
    category: "engagement",
    style: "Solitaire",
    collection: "Sovereign Collection",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k White Gold", "18k Yellow Gold", "18k Rose Gold"],
    price: 2750,
    description: "An architectural double-claw solitaire setting engineered specifically for clean step-cut emerald diamonds.",
    image: "/images/styles/solitaire.jpg",
    images: ["/images/styles/solitaire.jpg", "/images/metals/platinum.jpg"],
    metalImages: {
      "18k White Gold": "/images/styles/solitaire.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
      "Platinum": "/images/metals/platinum.jpg",
    },
    badge: "Architectural",
    compatibleShapes: ["Emerald", "Radiant"],
    settingDetails: ["Cathedral Setting", "Plain Band"],
  },
  {
    id: "ER-013",
    name: "Three Stone Radiance",
    category: "engagement",
    style: "Three Stone",
    collection: "Heritage Suite",
    metal: "18k White Gold",
    availableMetals: ["18k White Gold", "18k Yellow Gold", "18k Rose Gold", "Platinum"],
    price: 2950,
    description: "Flanked by graduated brilliant cut shoulder diamonds, representing past, present and eternal future.",
    image: "/images/styles/trilogy.jpg",
    images: ["/images/styles/trilogy.jpg", "/images/mah-hero-concept.png"],
    metalImages: {
      "18k White Gold": "/images/styles/trilogy.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
      "Platinum": "/images/metals/platinum.jpg",
    },
    badge: "Trilogy Classic",
    compatibleShapes: ["Round", "Oval", "Cushion"],
    settingDetails: ["Plain Band"],
  },
  {
    id: "ER-014",
    name: "Pear Solitaire",
    category: "engagement",
    style: "Solitaire",
    collection: "Sovereign Collection",
    metal: "18k White Gold",
    availableMetals: ["18k White Gold", "18k Yellow Gold", "18k Rose Gold", "Platinum"],
    price: 1850,
    description: "A V-prong tipped solitaire designed to protect and accentuate the elongated teardrop silhouette of a pear diamond.",
    image: "/images/styles/solitaire.jpg",
    images: ["/images/styles/solitaire.jpg", "/images/mah-hero-concept.png"],
    metalImages: {
      "18k White Gold": "/images/styles/solitaire.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
      "Platinum": "/images/metals/platinum.jpg",
    },
    badge: "Modern Icon",
    compatibleShapes: ["Pear", "Marquise"],
    settingDetails: ["Tapered Band"],
  },
  {
    id: "ER-015",
    name: "Cushion Halo",
    category: "engagement",
    style: "Halo",
    collection: "Celeste Collection",
    metal: "18k White Gold",
    availableMetals: ["18k White Gold", "18k Yellow Gold", "18k Rose Gold", "Platinum"],
    price: 2650,
    description: "A softly curved cushion-shaped halo featuring scalloped micropavé diamonds and a hidden under-gallery halo.",
    image: "/images/styles/halo.jpg",
    images: ["/images/styles/halo.jpg", "/images/mah-hero-concept.png"],
    metalImages: {
      "18k White Gold": "/images/styles/halo.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
      "Platinum": "/images/metals/platinum.jpg",
    },
    badge: "Bespoke Classic",
    compatibleShapes: ["Cushion", "Princess", "Radiant"],
    settingDetails: ["Hidden Halo", "Plain Band"],
  },
  {
    id: "ER-016",
    name: "Pavé Brilliance",
    category: "engagement",
    style: "Pavé",
    collection: "Luna Suite",
    metal: "18k White Gold",
    availableMetals: ["18k White Gold", "18k Yellow Gold", "18k Rose Gold", "Platinum"],
    price: 2250,
    description: "A continuous three-quarter band of French pavé diamonds seamlessly leading up to a classic four-claw centre head.",
    image: "/images/styles/diamond-band.jpg",
    images: ["/images/styles/diamond-band.jpg", "/images/mah-hero-concept.png"],
    metalImages: {
      "18k White Gold": "/images/styles/diamond-band.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
      "Platinum": "/images/metals/platinum.jpg",
    },
    badge: "London Classic",
    compatibleShapes: ["Round", "Oval", "Princess"],
    settingDetails: ["Plain Band"],
  },
  {
    id: "ER-017",
    name: "Vintage Love",
    category: "engagement",
    style: "Vintage",
    collection: "Heritage Suite",
    metal: "18k Yellow Gold",
    availableMetals: ["18k Yellow Gold", "18k White Gold", "18k Rose Gold", "Platinum"],
    price: 2350,
    description: "Intricate milgrain edging and hand-engraved scrollwork inspired by London's Edwardian jewellery ateliers.",
    image: "/images/styles/solitaire.jpg",
    images: ["/images/styles/solitaire.jpg", "/images/metals/yellow-gold.jpg"],
    metalImages: {
      "18k White Gold": "/images/styles/solitaire.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
      "Platinum": "/images/metals/platinum.jpg",
    },
    badge: "Heritage Edition",
    compatibleShapes: ["Round", "Oval", "Marquise"],
    settingDetails: ["Cathedral Setting"],
  },
  {
    id: "ER-001",
    name: "The Aster Solitaire",
    category: "engagement",
    style: "Solitaire",
    collection: "Sovereign Collection",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k Yellow Gold", "18k Rose Gold", "18k White Gold"],
    price: 1850,
    description: "An architectural four-claw setting with a refined, light-catching band handcrafted in our London atelier.",
    image: "/images/styles/solitaire.jpg",
    images: [
      "/images/styles/solitaire.jpg",
      "/images/mah-hero-concept.png",
      "/images/metals/platinum.jpg",
    ],
    metalImages: {
      "Platinum": "/images/styles/solitaire.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
      "18k White Gold": "/images/metals/white-gold.jpg",
    },
    badge: "Maison Signature",
    compatibleShapes: ["Round", "Oval", "Cushion", "Emerald", "Princess"],
    settingDetails: ["Plain Band"],
  },
  {
    id: "ER-002",
    name: "The Vendôme Solitaire",
    category: "engagement",
    style: "Solitaire",
    collection: "Vendôme Suite",
    metal: "18k Yellow Gold",
    availableMetals: ["18k Yellow Gold", "Platinum", "18k Rose Gold", "18k White Gold"],
    price: 1950,
    description: "A softly tapered cathedral shank with cut-corner talon claws designed for maximum light transmission.",
    image: "/images/styles/solitaire.jpg",
    images: [
      "/images/styles/solitaire.jpg",
      "/images/metals/yellow-gold.jpg",
      "/images/mah-hero-concept.png",
    ],
    metalImages: {
      "18k Yellow Gold": "/images/styles/solitaire.jpg",
      "Platinum": "/images/metals/platinum.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
      "18k White Gold": "/images/metals/white-gold.jpg",
    },
    badge: "London Classic",
    compatibleShapes: ["Oval", "Round", "Pear", "Marquise"],
    settingDetails: ["Cathedral Setting", "Tapered Band"],
  },
  {
    id: "ER-003",
    name: "The Celeste Halo",
    category: "engagement",
    style: "Halo",
    collection: "Celeste Collection",
    metal: "18k White Gold",
    availableMetals: ["Platinum", "18k White Gold", "18k Yellow Gold", "18k Rose Gold"],
    price: 2450,
    description: "A luminous micropavé halo setting engineered to amplify the brilliance of a round or cushion centre stone.",
    image: "/images/styles/halo.jpg",
    images: [
      "/images/styles/halo.jpg",
      "/images/metals/white-gold.jpg",
      "/images/styles/solitaire.jpg",
    ],
    metalImages: {
      "18k White Gold": "/images/styles/halo.jpg",
      "Platinum": "/images/metals/platinum.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
    },
    badge: "Bespoke Classic",
    compatibleShapes: ["Round", "Cushion", "Oval", "Princess"],
    settingDetails: ["Plain Band"],
  },
  {
    id: "ER-004",
    name: "The Aurelia Halo",
    category: "engagement",
    style: "Halo",
    collection: "Celeste Collection",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k Yellow Gold", "18k Rose Gold", "18k White Gold"],
    price: 2650,
    description: "An architectural step-cut halo tailored specifically for emerald and radiant cut certified diamonds.",
    image: "/images/styles/halo.jpg",
    images: [
      "/images/styles/halo.jpg",
      "/images/metals/platinum.jpg",
      "/images/mah-hero-concept.png",
    ],
    metalImages: {
      "Platinum": "/images/styles/halo.jpg",
      "18k White Gold": "/images/metals/white-gold.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
    },
    compatibleShapes: ["Emerald", "Radiant", "Asscher"],
    settingDetails: ["Cathedral Setting"],
  },
  {
    id: "ER-005",
    name: "The Elara Trilogy",
    category: "engagement",
    style: "Three Stone",
    collection: "Heritage Suite",
    metal: "18k Yellow Gold",
    availableMetals: ["18k Yellow Gold", "Platinum", "18k White Gold", "18k Rose Gold"],
    price: 2850,
    description: "A stately trilogy setting with tapered baguette side stones, honoring London's bespoke goldsmithing heritage.",
    image: "/images/styles/trilogy.jpg",
    images: [
      "/images/styles/trilogy.jpg",
      "/images/metals/yellow-gold.jpg",
      "/images/styles/solitaire.jpg",
    ],
    metalImages: {
      "18k Yellow Gold": "/images/styles/trilogy.jpg",
      "Platinum": "/images/metals/platinum.jpg",
      "18k White Gold": "/images/metals/white-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
    },
    badge: "Heritage Edition",
    compatibleShapes: ["Emerald", "Radiant", "Oval", "Round"],
    settingDetails: ["Plain Band", "Tapered Band"],
  },
  {
    id: "ER-006",
    name: "The Mayfair Trilogy",
    category: "engagement",
    style: "Three Stone",
    collection: "Heritage Suite",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k Yellow Gold", "18k Rose Gold", "18k White Gold"],
    price: 3100,
    description: "Graduated pear-cut shoulder stones framing a magnificent central certified diamond with flawless balance.",
    image: "/images/styles/trilogy.jpg",
    images: [
      "/images/styles/trilogy.jpg",
      "/images/metals/platinum.jpg",
      "/images/mah-hero-concept.png",
    ],
    metalImages: {
      "Platinum": "/images/styles/trilogy.jpg",
      "18k White Gold": "/images/metals/white-gold.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
    },
    badge: "Maison Signature",
    compatibleShapes: ["Round", "Oval", "Cushion", "Pear"],
    settingDetails: ["Plain Band"],
  },
  {
    id: "ER-007",
    name: "The Entrelacs Toi et Moi",
    category: "engagement",
    style: "Twist",
    collection: "Signatures",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k Yellow Gold", "18k Rose Gold", "18k White Gold"],
    price: 3400,
    description: "An intertwined twin-stone setting symbolizing two distinct paths converging into one harmonious journey.",
    image: "/images/styles/toi-et-moi.jpg",
    images: [
      "/images/styles/toi-et-moi.jpg",
      "/images/metals/platinum.jpg",
      "/images/styles/solitaire.jpg",
    ],
    metalImages: {
      "Platinum": "/images/styles/toi-et-moi.jpg",
      "18k White Gold": "/images/metals/white-gold.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
    },
    badge: "Haute Joaillerie",
    compatibleShapes: ["Pear", "Emerald", "Oval", "Round"],
    settingDetails: ["Tapered Band"],
  },
  {
    id: "ER-008",
    name: "The Luna Pavé",
    category: "engagement",
    style: "Pavé",
    collection: "Luna Suite",
    metal: "18k Rose Gold",
    availableMetals: ["18k Rose Gold", "Platinum", "18k White Gold", "18k Yellow Gold"],
    price: 2150,
    description: "A French-cut micropavé band handcrafted for a continuous, brilliant ribbon of pavé-set diamonds.",
    image: "/images/styles/diamond-band.jpg",
    images: [
      "/images/styles/diamond-band.jpg",
      "/images/metals/rose-gold.jpg",
      "/images/styles/solitaire.jpg",
    ],
    metalImages: {
      "18k Rose Gold": "/images/styles/diamond-band.jpg",
      "Platinum": "/images/metals/platinum.jpg",
      "18k White Gold": "/images/metals/white-gold.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
    },
    compatibleShapes: ["Round", "Oval", "Pear", "Marquise"],
    settingDetails: ["Plain Band"],
  },
  {
    id: "ER-009",
    name: "The Sovereign Pavé",
    category: "engagement",
    style: "Hidden Halo",
    collection: "Sovereign Collection",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k Yellow Gold", "18k Rose Gold", "18k White Gold"],
    price: 2350,
    description: "A scalloped pavé setting with concealed diamond gallery details beneath the centre stone.",
    image: "/images/styles/diamond-band.jpg",
    images: [
      "/images/styles/diamond-band.jpg",
      "/images/metals/platinum.jpg",
      "/images/mah-hero-concept.png",
    ],
    metalImages: {
      "Platinum": "/images/styles/diamond-band.jpg",
      "18k White Gold": "/images/metals/white-gold.jpg",
      "18k Yellow Gold": "/images/metals/yellow-gold.jpg",
      "18k Rose Gold": "/images/metals/rose-gold.jpg",
    },
    badge: "London Classic",
    compatibleShapes: ["Round", "Cushion", "Oval", "Princess", "Radiant"],
    settingDetails: ["Hidden Halo", "Cathedral Setting"],
  },

  // ==========================================
  // WEDDING RINGS (Section 10)
  // ==========================================
  {
    id: "WR-001",
    name: "Classic Diamond Band",
    category: "wedding",
    style: "Diamond",
    collection: "Sovereign Collection",
    metal: "18k White Gold",
    availableMetals: ["18k White Gold", "Platinum", "18k Yellow Gold", "18k Rose Gold"],
    price: 1250,
    gender: "women",
    width: "2.5mm",
    profile: "Court",
    isDiamond: true,
    description: "A continuous row of hand-selected brilliant cut certified diamonds in a scalloped claw setting.",
    image: "/images/styles/diamond-band.jpg",
    images: ["/images/styles/diamond-band.jpg", "/images/metals/white-gold.jpg"],
    badge: "Maison Signature",
  },
  {
    id: "WR-002",
    name: "Men's Brushed Band",
    category: "wedding",
    style: "Plain",
    collection: "Heritage Suite",
    metal: "18k Yellow Gold",
    availableMetals: ["18k Yellow Gold", "Platinum", "18k Rose Gold", "18k White Gold"],
    price: 850,
    gender: "men",
    width: "5mm",
    profile: "Flat Court",
    isDiamond: false,
    description: "A contemporary flat court wedding band featuring a satin-brushed finish and polished comfort-fit bevels.",
    image: "/images/metals/yellow-gold.jpg",
    images: ["/images/metals/yellow-gold.jpg", "/images/metals/platinum.jpg"],
    badge: "London Classic",
  },
  {
    id: "WR-003",
    name: "Sleek Comfort Band",
    category: "wedding",
    style: "Plain",
    collection: "Vendôme Suite",
    metal: "18k Rose Gold",
    availableMetals: ["18k Rose Gold", "18k Yellow Gold", "Platinum", "18k White Gold"],
    price: 750,
    gender: "unisex",
    width: "3mm",
    profile: "Traditional Court",
    isDiamond: false,
    description: "A soft curved silhouette with seamless silk-touch interior engineered for effortless daily wear.",
    image: "/images/metals/rose-gold.jpg",
    images: ["/images/metals/rose-gold.jpg", "/images/metals/yellow-gold.jpg"],
  },
  {
    id: "WR-004",
    name: "Milgrain Edge Band",
    category: "wedding",
    style: "Plain",
    collection: "Sovereign Collection",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k White Gold", "18k Yellow Gold", "18k Rose Gold"],
    price: 1150,
    gender: "unisex",
    width: "4mm",
    profile: "Flat Court",
    isDiamond: false,
    description: "Hand-applied vintage milgrain beading along the borders of solid 950 London-assayed platinum.",
    image: "/images/metals/platinum.jpg",
    images: ["/images/metals/platinum.jpg", "/images/styles/diamond-band.jpg"],
    badge: "Heritage Edition",
  },
  {
    id: "WR-005",
    name: "The Crown Pavé Band",
    category: "wedding",
    style: "Diamond",
    collection: "Sovereign Collection",
    metal: "18k White Gold",
    availableMetals: ["Platinum", "18k White Gold", "18k Yellow Gold", "18k Rose Gold"],
    price: 1650,
    gender: "women",
    width: "2mm",
    profile: "Court",
    isDiamond: true,
    description: "A refined diamond eternity band with scalloped claw settings designed to sit flush with your engagement ring.",
    image: "/images/styles/diamond-band.jpg",
    images: ["/images/styles/diamond-band.jpg", "/images/metals/white-gold.jpg"],
    badge: "Maison Signature",
  },
  {
    id: "WR-006",
    name: "The Eternity Whisper",
    category: "wedding",
    style: "Diamond",
    collection: "Luna Suite",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k White Gold", "18k Rose Gold", "18k Yellow Gold"],
    price: 2100,
    gender: "women",
    width: "1.8mm",
    profile: "Court",
    isDiamond: true,
    description: "A continuous micro-claw eternity ring set with calibrated D-F colour diamonds in 950 platinum.",
    image: "/images/styles/diamond-band.jpg",
    images: ["/images/styles/diamond-band.jpg", "/images/metals/platinum.jpg"],
    badge: "Bespoke Classic",
  },
  {
    id: "WR-007",
    name: "The Mayfair Heavy Court",
    category: "wedding",
    style: "Plain",
    collection: "Sovereign Collection",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k Yellow Gold", "18k Rose Gold"],
    price: 1450,
    gender: "men",
    width: "6mm",
    profile: "Traditional Court",
    isDiamond: false,
    description: "A substantial 6mm flat court band in solid 950 platinum with a hand-burnished satin exterior.",
    image: "/images/metals/platinum.jpg",
    images: ["/images/metals/platinum.jpg", "/images/metals/yellow-gold.jpg"],
    badge: "Essential",
  },
  {
    id: "WR-008",
    name: "The Baguette Channel Band",
    category: "wedding",
    style: "Diamond",
    collection: "Heritage Suite",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k White Gold", "18k Yellow Gold"],
    price: 2450,
    gender: "unisex",
    width: "3.5mm",
    profile: "Flat",
    isDiamond: true,
    description: "Calibrated step-cut baguette diamonds set flush in an architectural channel of pure 950 platinum.",
    image: "/images/styles/diamond-band.jpg",
    images: ["/images/styles/diamond-band.jpg", "/images/metals/platinum.jpg"],
    badge: "Haute Joaillerie",
  },
  {
    id: "WR-009",
    name: "The Chevron Contour Band",
    category: "wedding",
    style: "Diamond",
    collection: "Luna Suite",
    metal: "18k Yellow Gold",
    availableMetals: ["18k Yellow Gold", "Platinum", "18k Rose Gold", "18k White Gold"],
    price: 1380,
    gender: "women",
    width: "2mm",
    profile: "Contour",
    isDiamond: true,
    description: "A contoured V-shaped diamond band sculpted to nest intimately against solitaire and halo engagement rings.",
    image: "/images/styles/diamond-band.jpg",
    images: ["/images/styles/diamond-band.jpg", "/images/metals/yellow-gold.jpg"],
  },

  // ==========================================
  // JEWELLERY & SIGNATURES (Section 12 & 13)
  // ==========================================
  {
    id: "JW-001",
    name: "Aster Diamond Pendant",
    category: "jewellery",
    style: "Necklace",
    collection: "Sovereign Collection",
    metal: "18k White Gold",
    availableMetals: ["18k White Gold", "Platinum", "18k Yellow Gold"],
    price: 1250,
    description: "A refined solitaire diamond pendant suspended on a fine Italian cable chain.",
    image: "/images/styles/solitaire.jpg",
    images: [
      "/images/styles/solitaire.jpg",
      "/images/metals/white-gold.jpg",
    ],
    badge: "Haute Joaillerie",
  },
  {
    id: "JW-002",
    name: "Celeste Diamond Studs",
    category: "jewellery",
    style: "Earrings",
    collection: "Celeste Collection",
    metal: "18k Yellow Gold",
    availableMetals: ["18k Yellow Gold", "Platinum", "18k White Gold"],
    price: 1450,
    description: "Classic four-claw martini studs designed for maximum diamond illumination and everyday luxury.",
    image: "/images/styles/halo.jpg",
    images: [
      "/images/styles/halo.jpg",
      "/images/metals/yellow-gold.jpg",
    ],
  },
  {
    id: "JW-003",
    name: "Luna Riviera Bracelet",
    category: "jewellery",
    style: "Bracelet",
    collection: "Luna Suite",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k White Gold", "18k Yellow Gold"],
    price: 4800,
    description: "A fluid tennis bracelet featuring graduated brilliant-cut diamonds with an invisible safety clasp.",
    image: "/images/styles/diamond-band.jpg",
    images: [
      "/images/styles/diamond-band.jpg",
      "/images/metals/platinum.jpg",
    ],
    badge: "Haute Joaillerie",
  },
  {
    id: "JW-004",
    name: "Vendôme Medallion Pendant",
    category: "jewellery",
    style: "Necklace",
    collection: "Vendôme Suite",
    metal: "18k Yellow Gold",
    availableMetals: ["18k Yellow Gold", "Platinum", "18k Rose Gold"],
    price: 1950,
    description: "An octagonal medallion in 18ct gold set with a brilliant centre diamond and hand-engraved radial facets.",
    image: "/images/styles/solitaire.jpg",
    images: [
      "/images/styles/solitaire.jpg",
      "/images/metals/yellow-gold.jpg",
    ],
  },
  {
    id: "JW-005",
    name: "Royal Drop Earrings",
    category: "jewellery",
    style: "Earrings",
    collection: "Heritage Suite",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k White Gold"],
    price: 3200,
    description: "Articulated diamond drop earrings designed with graduated pear and round brilliant diamonds.",
    image: "/images/styles/trilogy.jpg",
    images: [
      "/images/styles/trilogy.jpg",
      "/images/metals/platinum.jpg",
    ],
    badge: "Haute Joaillerie",
  },
  {
    id: "JW-006",
    name: "Sovereign Diamond Bangle",
    category: "jewellery",
    style: "Bracelet",
    collection: "Sovereign Collection",
    metal: "18k Yellow Gold",
    availableMetals: ["18k Yellow Gold", "Platinum", "18k Rose Gold"],
    price: 5400,
    description: "A structured hinged bangle pave-set with two rows of brilliant diamonds and a concealed push release.",
    image: "/images/styles/diamond-band.jpg",
    images: [
      "/images/styles/diamond-band.jpg",
      "/images/metals/yellow-gold.jpg",
    ],
  },
  {
    id: "JW-007",
    name: "Octagonal Signature Solitaire Ring",
    category: "jewellery",
    style: "Ring",
    collection: "Signatures",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k Yellow Gold", "18k Rose Gold"],
    price: 3850,
    description: "The definitive MAH Signature creation: a cut-corner octagonal collet hand-forged in solid 950 platinum.",
    image: "/images/mah-hero-concept.png",
    images: [
      "/images/mah-hero-concept.png",
      "/images/styles/solitaire.jpg",
      "/images/metals/platinum.jpg",
    ],
    badge: "MAH Signature",
  },
  {
    id: "JW-008",
    name: "Clover Blossom Diamond Pendant",
    category: "jewellery",
    style: "Pendant",
    collection: "Vendôme Suite",
    metal: "18k Yellow Gold",
    availableMetals: ["18k Yellow Gold", "18k White Gold", "Platinum"],
    price: 1650,
    description: "A floral quadrant clover motif pave-set with calibrated brilliant diamonds on a 45cm fine chain.",
    image: "/images/styles/solitaire.jpg",
    images: [
      "/images/styles/solitaire.jpg",
      "/images/metals/yellow-gold.jpg",
    ],
  },
  {
    id: "JW-009",
    name: "Sovereign Men's Faceted Band",
    category: "jewellery",
    style: "Men's Jewellery",
    collection: "Sovereign Collection",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k White Gold", "18k Yellow Gold"],
    price: 1850,
    description: "A substantial 6mm bevelled men's band in heavy platinum with micro-knurled central channel.",
    image: "/images/styles/diamond-band.jpg",
    images: [
      "/images/styles/diamond-band.jpg",
      "/images/metals/platinum.jpg",
    ],
  },
  {
    id: "JW-010",
    name: "Royal Diamond Eternity Ring",
    category: "jewellery",
    style: "Ring",
    collection: "Heritage Suite",
    metal: "Platinum",
    availableMetals: ["Platinum", "18k White Gold", "18k Yellow Gold"],
    price: 4200,
    description: "A complete circle of uniform brilliant-cut diamonds secured in shared four-claw settings.",
    image: "/images/styles/diamond-band.jpg",
    images: [
      "/images/styles/diamond-band.jpg",
      "/images/metals/platinum.jpg",
    ],
  },
];

export const diamonds: Diamond[] = [
  // Wireframe Section 05D Exact Match Exemplar
  { id: "D-05D", type: "Natural", shape: "Round", carat: 3.52, colour: "D", clarity: "VVS1", cut: "Excellent", certificate: "GIA", reportNumber: "2476843210", price: 95550, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 61.8, table: 57.0, measurements: "9.78 – 9.82 × 6.05 mm", ratio: 1.00, culet: "None", girdle: "Medium", status: "available" },
  // Wireframe Section 05C Exact Match Exemplars & Natural Diamonds
  { id: "D-001", type: "Natural", shape: "Round", carat: 1.01, colour: "D", clarity: "VS1", cut: "Excellent", certificate: "GIA", reportNumber: "2476843210", price: 6420, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 61.8, table: 57.0, measurements: "6.42 – 6.45 × 3.97 mm", ratio: 1.00, culet: "None", girdle: "Thin to Medium", status: "available" },
  { id: "D-002", type: "Lab-grown", shape: "Round", carat: 1.00, colour: "E", clarity: "VS1", cut: "Excellent", certificate: "IGI", reportNumber: "LG568377401", price: 6280, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 61.5, table: 58.0, measurements: "6.40 – 6.43 × 3.95 mm", ratio: 1.00, culet: "None", girdle: "Medium", status: "available" },
  { id: "D-003", type: "Natural", shape: "Round", carat: 1.02, colour: "E", clarity: "VVS2", cut: "Excellent", certificate: "GIA", reportNumber: "6461769012", price: 6850, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 61.9, table: 56.5, measurements: "6.45 – 6.48 × 3.99 mm", ratio: 1.00, culet: "None", girdle: "Medium", status: "available" },
  { id: "D-004", type: "Natural", shape: "Round", carat: 1.01, colour: "F", clarity: "VS1", cut: "Excellent", certificate: "GIA", reportNumber: "1472846508", price: 6150, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 61.7, table: 57.5, measurements: "6.41 – 6.44 × 3.96 mm", ratio: 1.00, culet: "None", girdle: "Thin to Medium", status: "available" },
  { id: "D-S101", type: "Natural", shape: "Round", carat: 0.50, colour: "F", clarity: "VS1", cut: "Excellent", certificate: "GIA", reportNumber: "2198472910", price: 1850, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 61.2, table: 57.0, measurements: "5.12 – 5.15 × 3.16 mm", ratio: 1.00, culet: "None", girdle: "Medium", status: "available" },
  { id: "D-S102", type: "Natural", shape: "Round", carat: 0.70, colour: "E", clarity: "VS2", cut: "Excellent", certificate: "GIA", reportNumber: "5183920194", price: 2620, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 61.8, table: 56.5, measurements: "5.68 – 5.71 × 3.52 mm", ratio: 1.00, culet: "None", girdle: "Medium", status: "available" },
  { id: "D-S103", type: "Natural", shape: "Round", carat: 1.00, colour: "D", clarity: "VS1", cut: "Excellent", certificate: "GIA", reportNumber: "6293847192", price: 4450, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 60.9, table: 57.0, measurements: "6.40 – 6.44 × 3.92 mm", ratio: 1.00, culet: "None", girdle: "Medium", status: "available" },
  { id: "D-S104", type: "Natural", shape: "Round", carat: 0.90, colour: "G", clarity: "SI1", cut: "Excellent", certificate: "IGI", price: 3150, polish: "Excellent", symmetry: "Very Good", fluorescence: "Faint", depth: 62.1, table: 58.0, status: "available" },
  { id: "D-S105", type: "Natural", shape: "Round", carat: 1.20, colour: "E", clarity: "VS1", cut: "Excellent", certificate: "GIA", price: 6850, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 61.5, table: 57.0, status: "available" },
  { id: "D-S106", type: "Natural", shape: "Round", carat: 1.50, colour: "F", clarity: "VS2", cut: "Excellent", certificate: "GIA", price: 8950, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 61.9, table: 56.0, status: "available" },
  { id: "D-S107", type: "Natural", shape: "Round", carat: 2.01, colour: "D", clarity: "VS1", cut: "Excellent", certificate: "GIA", price: 15800, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 61.0, table: 57.5, status: "available" },
  { id: "D-S108", type: "Natural", shape: "Round", carat: 0.34, colour: "H", clarity: "SI2", cut: "Very Good", certificate: "IGI", price: 820, polish: "Very Good", symmetry: "Very Good", fluorescence: "Medium", depth: 62.8, table: 59.0, status: "available" },
  { id: "D-S109", type: "Natural", shape: "Oval", carat: 1.21, colour: "H", clarity: "VS2", cut: "Excellent", certificate: "GIA", price: 7100, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 63.2, table: 58.0, status: "available" },
  { id: "D-S110", type: "Natural", shape: "Oval", carat: 1.50, colour: "E", clarity: "VVS1", cut: "Excellent", certificate: "GIA", price: 11200, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 62.8, table: 57.0, status: "available" },
  { id: "D-S111", type: "Natural", shape: "Emerald", carat: 1.10, colour: "F", clarity: "VVS2", cut: "Very Good", certificate: "GIA", price: 7950, polish: "Excellent", symmetry: "Very Good", fluorescence: "None", depth: 65.4, table: 64.0, status: "available" },
  { id: "D-S112", type: "Natural", shape: "Emerald", carat: 2.05, colour: "D", clarity: "VS1", cut: "Excellent", certificate: "GIA", price: 18400, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 64.8, table: 63.0, status: "available" },
  { id: "D-S113", type: "Natural", shape: "Pear", carat: 1.35, colour: "E", clarity: "VS1", cut: "Excellent", certificate: "GIA", price: 8400, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 61.7, table: 59.0, status: "available" },
  { id: "D-S114", type: "Natural", shape: "Cushion", carat: 1.52, colour: "F", clarity: "VS1", cut: "Excellent", certificate: "GIA", price: 9200, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 66.2, table: 61.0, status: "available" },
  { id: "D-S115", type: "Natural", shape: "Princess", carat: 1.40, colour: "F", clarity: "VVS1", cut: "Ideal", certificate: "GIA", price: 8600, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 71.5, table: 69.0, status: "available" },
  { id: "D-S116", type: "Natural", shape: "Radiant", carat: 1.55, colour: "G", clarity: "VS1", cut: "Excellent", certificate: "GIA", price: 8900, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 67.0, table: 65.0, status: "available" },
  { id: "D-S117", type: "Natural", shape: "Marquise", carat: 1.25, colour: "E", clarity: "VS1", cut: "Excellent", certificate: "GIA", price: 7800, polish: "Excellent", symmetry: "Very Good", fluorescence: "None", depth: 61.0, table: 58.0, status: "available" },
  { id: "D-S118", type: "Natural", shape: "Asscher", carat: 1.30, colour: "E", clarity: "VVS2", cut: "Excellent", certificate: "GIA", price: 8100, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 68.0, table: 62.0, status: "available" },
  { id: "D-S119", type: "Natural", shape: "Heart", carat: 1.15, colour: "G", clarity: "VS2", cut: "Very Good", certificate: "GIA", price: 6800, polish: "Very Good", symmetry: "Very Good", fluorescence: "None", depth: 59.5, table: 57.0, status: "available" },

  // Lab-Grown Diamonds
  { id: "D-S201", type: "Lab-grown", shape: "Round", carat: 1.50, colour: "E", clarity: "VS1", cut: "Ideal", certificate: "IGI", price: 1850, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 61.5, table: 56.5, status: "available" },
  { id: "D-S202", type: "Lab-grown", shape: "Round", carat: 2.05, colour: "D", clarity: "VVS1", cut: "Ideal", certificate: "IGI", price: 2950, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 61.2, table: 57.0, status: "available" },
  { id: "D-S203", type: "Lab-grown", shape: "Round", carat: 3.10, colour: "E", clarity: "VVS2", cut: "Ideal", certificate: "IGI", price: 4600, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 61.8, table: 56.0, status: "available" },
  { id: "D-S204", type: "Lab-grown", shape: "Oval", carat: 1.75, colour: "D", clarity: "VVS2", cut: "Ideal", certificate: "IGI", price: 2250, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 62.5, table: 58.0, status: "available" },
  { id: "D-S205", type: "Lab-grown", shape: "Oval", carat: 2.50, colour: "E", clarity: "VS1", cut: "Ideal", certificate: "IGI", price: 3400, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 63.0, table: 57.5, status: "available" },
  { id: "D-S206", type: "Lab-grown", shape: "Emerald", carat: 1.80, colour: "E", clarity: "VS1", cut: "Excellent", certificate: "IGI", price: 2100, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 65.0, table: 63.0, status: "available" },
  { id: "D-S207", type: "Lab-grown", shape: "Emerald", carat: 2.60, colour: "D", clarity: "VVS1", cut: "Ideal", certificate: "IGI", price: 3850, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 64.5, table: 62.0, status: "available" },
  { id: "D-S208", type: "Lab-grown", shape: "Pear", carat: 1.72, colour: "F", clarity: "VS2", cut: "Excellent", certificate: "IGI", price: 2150, polish: "Excellent", symmetry: "Very Good", fluorescence: "None", depth: 61.4, table: 58.5, status: "available" },
  { id: "D-S209", type: "Lab-grown", shape: "Cushion", carat: 2.01, colour: "G", clarity: "VVS2", cut: "Ideal", certificate: "IGI", price: 2850, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 66.8, table: 61.5, status: "available" },
  { id: "D-S210", type: "Lab-grown", shape: "Radiant", carat: 2.10, colour: "D", clarity: "VVS2", cut: "Ideal", certificate: "IGI", price: 3100, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 67.2, table: 65.0, status: "available" },
  { id: "D-S211", type: "Lab-grown", shape: "Asscher", carat: 1.65, colour: "E", clarity: "VS1", cut: "Ideal", certificate: "IGI", price: 2400, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 67.8, table: 61.0, status: "available" },
  { id: "D-S212", type: "Lab-grown", shape: "Princess", carat: 1.85, colour: "E", clarity: "VVS2", cut: "Ideal", certificate: "IGI", price: 2650, polish: "Excellent", symmetry: "Excellent", fluorescence: "None", depth: 71.0, table: 68.0, status: "available" },
  { id: "D-S213", type: "Lab-grown", shape: "Marquise", carat: 1.60, colour: "F", clarity: "VS1", cut: "Excellent", certificate: "IGI", price: 2350, polish: "Excellent", symmetry: "Very Good", fluorescence: "None", depth: 61.5, table: 58.0, status: "available" },
  { id: "D-S214", type: "Lab-grown", shape: "Heart", carat: 1.50, colour: "E", clarity: "VS1", cut: "Very Good", certificate: "IGI", price: 2200, polish: "Very Good", symmetry: "Very Good", fluorescence: "None", depth: 60.0, table: 57.0, status: "available" },
];

export type CurrencyCode = "GBP" | "USD" | "EUR" | "AED";

export const CURRENCY_RATES: Record<CurrencyCode, { rate: number; symbol: string; locale: string }> = {
  GBP: { rate: 1.0, symbol: "£", locale: "en-GB" },
  USD: { rate: 1.28, symbol: "$", locale: "en-US" },
  EUR: { rate: 1.18, symbol: "€", locale: "de-DE" },
  AED: { rate: 4.70, symbol: "د.إ", locale: "en-AE" },
};

export const money = (value: number, overrideCurrency?: CurrencyCode) => {
  let currency: CurrencyCode = overrideCurrency || "GBP";
  if (!overrideCurrency && typeof window !== "undefined") {
    try {
      const saved = localStorage.getItem("mah-currency") as CurrencyCode;
      if (saved && CURRENCY_RATES[saved]) {
        currency = saved;
      }
    } catch {}
  }
  const config = CURRENCY_RATES[currency] || CURRENCY_RATES.GBP;
  const converted = Math.round(value * config.rate);
  return new Intl.NumberFormat(config.locale, {
    style: "currency",
    currency: currency,
    maximumFractionDigits: 0,
  }).format(converted);
};

export const getProduct = (id?: string | null) => products.find((item) => item.id === id) || products[0];
export const getDiamond = (id?: string | null) => diamonds.find((item) => item.id === id) || diamonds[0];

